// ignore_for_file: constant_identifier_names
// Generated by scripts/build-tokens.js from src/add-os/theme/tokens.ts — DO NOT EDIT this file.
// Source: src/add-os/theme/tokens.ts

import 'dart:ui';

/// ADD OS brand primitives — verbatim from the ADD Brand Guideline 2026.
class AddBrand {
  AddBrand._();
  static const Color charcoalBackbone = Color(0xFF43474F);
  static const Color warmMist = Color(0xFFE2DDDB);
  static const Color smartOlive = Color(0xFF809C66);
  static const Color softGrowthGreen = Color(0xFFB8D098);
  static const Color aleppoEconomicOrange = Color(0xFFDC4128);
  static const Color aleppoStone = Color(0xFFCDC2AF);
  static const Color antiqueCopper = Color(0xFFA97C57);
  static const Color levantDeepTeal = Color(0xFF314550);
  static const Color signalCyan = Color(0xFF00BFDF);
  static const Color deepTeal = Color(0xFF007F91);
}

/// ADD OS semantic tokens — light mode.
/// Dark mode is out of scope for v1; add an `AddColorsDark` class when it lands.
class AddColors {
  AddColors._();
  static const Color primaryBase = Color(0xFF007F91);
  static const Color primaryHover = Color(0xFF006977);
  static const Color primaryPressed = Color(0xFF00525E);
  static const Color primarySuppl = Color(0xFF006977);
  static const Color primaryOn = Color(0xFFFFFFFF);
  static const Color primaryText = Color(0xFF006B7A);
  static const Color successBase = Color(0xFF657C50);
  static const Color successHover = Color(0xFF586C46);
  static const Color successPressed = Color(0xFF4C5D3C);
  static const Color successSuppl = Color(0xFF586C46);
  static const Color successOn = Color(0xFFFFFFFF);
  static const Color successText = Color(0xFF556843);
  static const Color warningBase = Color(0xFFE7B155);
  static const Color warningHover = Color(0xFFEABB6B);
  static const Color warningPressed = Color(0xFFEDC682);
  static const Color warningSuppl = Color(0xFFEABB6B);
  static const Color warningOn = Color(0xFF43474F);
  static const Color warningText = Color(0xFF845A13);
  static const Color dangerBase = Color(0xFFD93D23);
  static const Color dangerHover = Color(0xFFC3371F);
  static const Color dangerPressed = Color(0xFFAD311C);
  static const Color dangerSuppl = Color(0xFFC3371F);
  static const Color dangerOn = Color(0xFFFFFFFF);
  static const Color dangerText = Color(0xFFB4321D);
  static const Color infoBase = Color(0xFF007F91);
  static const Color infoHover = Color(0xFF006977);
  static const Color infoPressed = Color(0xFF00525E);
  static const Color infoSuppl = Color(0xFF006977);
  static const Color infoOn = Color(0xFFFFFFFF);
  static const Color infoText = Color(0xFF006B7A);
  static const Color body = Color(0xFFE2DDDB);
  static const Color surface = Color(0xFFFFFFFF);
  static const Color surfaceRaised = Color(0xFFFFFFFF);
  static const Color surfaceSunken = Color(0xFFEDEAE8);
  static const Color inputFill = Color(0xFFEFECEB);
  static const Color border = Color(0xFFCDC2AF);
  static const Color borderStrong = Color(0xFF7F7B76);
  static const Color textPrimary = Color(0xFF43474F);
  static const Color textSecondary = Color(0xFF565B65);
  static const Color textMuted = Color(0xFF5A606B);
  static const Color textOnDark = Color(0xFFE2DDDB);
  static const Color focusRingInner = Color(0xFF314550);
  static const Color focusRingOuter = Color(0xFFFFFFFF);
}

/// Per-language type scale. Arabic runs larger and looser than Latin.
class AddTypeScale {
  AddTypeScale._();
  static const double ar_captionSize = 13;
  static const double ar_captionLineHeight = 1.6;
  static const double ar_bodySmSize = 15;
  static const double ar_bodySmLineHeight = 1.65;
  static const double ar_bodySize = 17;
  static const double ar_bodyLineHeight = 1.7;
  static const double ar_leadSize = 19;
  static const double ar_leadLineHeight = 1.65;
  static const double ar_h6Size = 13;
  static const double ar_h6LineHeight = 1.5;
  static const double ar_h5Size = 15;
  static const double ar_h5LineHeight = 1.5;
  static const double ar_h4Size = 19;
  static const double ar_h4LineHeight = 1.45;
  static const double ar_h3Size = 23;
  static const double ar_h3LineHeight = 1.4;
  static const double ar_h2Size = 27;
  static const double ar_h2LineHeight = 1.38;
  static const double ar_h1Size = 31;
  static const double ar_h1LineHeight = 1.35;
  static const double en_captionSize = 12;
  static const double en_captionLineHeight = 1.4;
  static const double en_bodySmSize = 14;
  static const double en_bodySmLineHeight = 1.45;
  static const double en_bodySize = 16;
  static const double en_bodyLineHeight = 1.5;
  static const double en_leadSize = 18;
  static const double en_leadLineHeight = 1.5;
  static const double en_h6Size = 12;
  static const double en_h6LineHeight = 1.3;
  static const double en_h5Size = 14;
  static const double en_h5LineHeight = 1.3;
  static const double en_h4Size = 18;
  static const double en_h4LineHeight = 1.3;
  static const double en_h3Size = 22;
  static const double en_h3LineHeight = 1.28;
  static const double en_h2Size = 26;
  static const double en_h2LineHeight = 1.26;
  static const double en_h1Size = 30;
  static const double en_h1LineHeight = 1.25;
}

class AddRadius {
  AddRadius._();
  static const double small = 4;
  static const double default = 8;
  static const double large = 12;
  static const double pill = 999;
}

class AddSpace {
  AddSpace._();
  static const double s0 = 0;
  static const double s1 = 2;
  static const double s2 = 4;
  static const double s3 = 6;
  static const double s4 = 8;
  static const double s5 = 12;
  static const double s6 = 16;
  static const double s7 = 20;
  static const double s8 = 24;
  static const double s9 = 32;
  static const double s10 = 40;
}
