/**
 * ADD OS — token generator.  `npm run tokens`
 *
 * ONE source: src/add-os/theme/tokens.ts (hand-authored).
 * MANY targets, because ADD OS is not the only consumer — a Flutter member app,
 * a Nuxt public site and a reception kiosk read the same tokens.
 *
 *   tokens.ts
 *     ├──▶ src/add-os/theme/tokens.json           W3C DTCG — neutral, canonical
 *     ├──▶ src/add-os/theme/tokens.generated.css  CSS custom properties + Tailwind @theme
 *     ├──▶ src/add-os/theme/tokens.dart           Flutter / Dart
 *     ├──▶ figma-tokens.json                      Figma Tokens plugin
 *     └──▶ src/design-tokens.json                 the Pinx runtime chain
 *
 * The canonical artifact is DTCG, not any one tool's format. Every other output
 * is a TRANSFORMER over it — add a consumer by adding a transformer, never by
 * hand-maintaining a second palette.
 *
 * ── Why this also writes src/design-tokens.json directly ────────────────────
 * The pre-existing `scripts/tokens-tool.js` converts figma-tokens.json →
 * src/design-tokens.json, but it is INTERACTIVE (@clack/prompts) and cannot run
 * in CI or a scripted build. Emitting that file here makes `npm run tokens` a
 * single non-interactive command. `tokens-tool.js` is left untouched and still
 * works for anyone importing a palette back from Figma.
 *
 * Run with plain `node` — Node 24 strips TypeScript types natively, so tokens.ts
 * is imported directly with no build step.
 */

import path from "node:path"
import process from "node:process"
import { fileURLToPath, pathToFileURL } from "node:url"
import fs from "fs-extra"

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const THEME_DIR = path.join(ROOT, "src", "add-os", "theme")

// pathToFileURL, not a bare path: on Windows an absolute path starts with a
// drive letter, which the ESM loader reads as an unsupported "c:" URL scheme.
const T = await import(pathToFileURL(path.join(THEME_DIR, "tokens.ts")).href)

const {
	brand,
	DERIVATIONS,
	semantic,
	component,
	THEME_MODES,
	DARK_MODE_SUPPORTED,
	fontFamily,
	fontWeight,
	typeScale,
	SUPPORTED_LANGS,
	space,
	radius,
	borderWidth,
	elevation,
	state
} = T

const kebab = s => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase()
const banner = name => `Generated by scripts/build-tokens.js from src/add-os/theme/tokens.ts — DO NOT EDIT ${name}.`

/** Reverse lookup: literal hex → brand token name, so DTCG can emit real aliases. */
const BRAND_BY_HEX = new Map(Object.entries(brand).map(([k, v]) => [v.toUpperCase(), kebab(k)]))
const DERIVED_BY_HEX = new Map(
	Object.entries(DERIVATIONS).map(([k, d]) => [d.value.toUpperCase(), { name: kebab(k), ...d }])
)

// ════════════════════════════════════════════════════════════════════════════
// 1. W3C DTCG — the canonical, tool-neutral artifact
//    https://tr.designtokens.org/format/
// ════════════════════════════════════════════════════════════════════════════

/**
 * Emits a colour as a DTCG alias when it is a brand primitive, otherwise as a
 * literal carrying its provenance. That is what makes the tier relationship
 * MACHINE-READABLE rather than a comment: a consumer can resolve `semantic.
 * primary` back to `brand.deep-teal` and know it is ADD's colour, not ours.
 */
function colorToken(hex, extra = {}) {
	const key = String(hex).toUpperCase()
	const brandName = BRAND_BY_HEX.get(key)

	if (brandName) {
		return { $value: `{brand.${brandName}}`, $extensions: { "com.add-os": { provenance: "brand", ...extra } } }
	}

	const derived = DERIVED_BY_HEX.get(key)
	if (derived) {
		return {
			$value: hex,
			$description: derived.note,
			$extensions: {
				"com.add-os": {
					provenance: derived.provenance,
					derivedFrom: derived.from ? `{brand.${kebab(derived.from)}}` : null,
					...extra
				}
			}
		}
	}

	// An interaction variant: same hue as its base, lightness moved for contrast.
	return { $value: hex, $extensions: { "com.add-os": { provenance: "adjusted", ...extra } } }
}

function buildDtcg() {
	const doc = {
		$description: `ADD OS design tokens. ${banner("this file")}`,
		$extensions: {
			"com.add-os": {
				source: "src/add-os/theme/tokens.ts",
				guideline: "ADD Brand Guideline 2026",
				audit: "docs/brand/PHASE-0-AUDIT.md",
				modes: [...THEME_MODES],
				darkModeSupported: DARK_MODE_SUPPORTED
			}
		},

		brand: { $type: "color" },
		semantic: {},
		component: {},
		typography: {},
		space: { $type: "dimension" },
		radius: { $type: "dimension" },
		"border-width": { $type: "dimension" },
		elevation: { $type: "shadow" },
		state: {}
	}

	for (const [name, hex] of Object.entries(brand)) {
		doc.brand[kebab(name)] = { $value: hex }
	}

	for (const mode of THEME_MODES) {
		const s = semantic[mode]
		const group = { $type: "color" }

		for (const [role, v] of Object.entries(s)) {
			if (typeof v === "string") {
				group[kebab(role)] = colorToken(v, { role: kebab(role) })
				continue
			}
			// An InteractiveColor: fill states plus its guaranteed text colour.
			group[kebab(role)] = {
				base: colorToken(v.base, { role: kebab(role) }),
				hover: colorToken(v.hover, { role: kebab(role), state: "hover" }),
				pressed: colorToken(v.pressed, { role: kebab(role), state: "pressed" }),
				suppl: colorToken(v.suppl, { role: kebab(role), state: "suppl" }),
				on: {
					...colorToken(v.on, { role: kebab(role) }),
					$description: `The ONLY approved text colour on ${kebab(role)} fills.`
				},
				text: {
					...colorToken(v.text, { role: kebab(role) }),
					$description: `${kebab(role)} as text/icon — clears AA on both surface and body.`
				}
			}
		}
		doc.semantic[mode] = group
	}

	for (const mode of THEME_MODES) {
		const group = {}
		for (const [area, values] of Object.entries(component[mode])) {
			group[kebab(area)] = Object.fromEntries(
				Object.entries(values).map(([k, v]) => [
					kebab(k),
					/^(?:#|rgb)/i.test(v) ? { $type: "color", ...colorToken(v) } : { $value: v }
				])
			)
		}
		doc.component[mode] = group
	}

	doc.typography = {
		family: Object.fromEntries(
			Object.entries(fontFamily).map(([k, v]) => [kebab(k), { $type: "fontFamily", $value: v }])
		),
		weight: Object.fromEntries(
			Object.entries(fontWeight).map(([k, v]) => [kebab(k), { $type: "fontWeight", $value: v }])
		),
		scale: Object.fromEntries(
			SUPPORTED_LANGS.map(lang => [
				lang,
				{
					$description:
						lang === "ar"
							? "Arabic runs one step larger and materially looser — the script needs vertical room Latin does not."
							: "Latin scale.",
					...Object.fromEntries(
						Object.entries(typeScale[lang]).map(([step, v]) => [
							step,
							{
								$type: "typography",
								$value: { fontSize: v.fontSize, lineHeight: v.lineHeight }
							}
						])
					)
				}
			])
		)
	}

	for (const [k, v] of Object.entries(space)) doc.space[k] = { $value: v }
	for (const [k, v] of Object.entries(radius)) doc.radius[kebab(k)] = { $value: v }
	for (const [k, v] of Object.entries(borderWidth)) doc["border-width"][kebab(k)] = { $value: v }
	for (const [k, v] of Object.entries(elevation)) doc.elevation[kebab(k)] = { $type: "shadow", $value: v }
	for (const [group, values] of Object.entries(state)) {
		doc.state[kebab(group)] = Object.fromEntries(Object.entries(values).map(([k, v]) => [kebab(k), { $value: v }]))
	}

	return doc
}

// ════════════════════════════════════════════════════════════════════════════
// 2. CSS transformer — custom properties + Tailwind v4 @theme
//
// Only the tokens Pinx does NOT already publish. The theme store writes
// --primary-color, --border-color and friends INLINE on <html>, and inline
// styles beat any :root rule, so re-declaring them here would be dead code at
// best. Everything below is prefixed `--add-` and cannot collide.
// ════════════════════════════════════════════════════════════════════════════

function buildCss() {
	const L = semantic.light
	const C = component.light
	const out = []

	out.push(`/* ${banner("this file")} */`)
	out.push(`/* Source: src/add-os/theme/tokens.ts · Audit: docs/brand/PHASE-0-AUDIT.md */\n`)
	out.push(":root {")

	out.push("\t/* ── brand primitives (Tier 1) ── */")
	for (const [k, v] of Object.entries(brand)) out.push(`\t--add-brand-${kebab(k)}: ${v};`)

	out.push("\n\t/* ── semantic fills + their guaranteed text colour (Tier 2) ── */")
	for (const role of ["primary", "success", "warning", "danger", "info"]) {
		const v = L[role]
		out.push(`\t--add-${role}: ${v.base};`)
		out.push(`\t--add-${role}-hover: ${v.hover};`)
		out.push(`\t--add-${role}-pressed: ${v.pressed};`)
		out.push(`\t--add-${role}-on: ${v.on};`)
		out.push(`\t--add-${role}-text: ${v.text};`)
	}

	out.push("\n\t/* ── surfaces ── */")
	for (const k of ["body", "surface", "surfaceRaised", "surfaceSunken", "inputFill"])
		out.push(`\t--add-${kebab(k)}: ${L[k]};`)

	out.push("\n\t/* ── borders · `border-strong` is the 3:1 one (WCAG 1.4.11) ── */")
	out.push(`\t--add-border: ${L.border};`)
	out.push(`\t--add-border-strong: ${L.borderStrong};`)
	for (const [k, v] of Object.entries(borderWidth)) out.push(`\t--add-border-width-${kebab(k)}: ${v};`)

	out.push("\n\t/* ── text ── */")
	for (const k of ["textPrimary", "textSecondary", "textMuted", "textOnDark"])
		out.push(`\t--add-${kebab(k)}: ${L[k]};`)

	out.push("\n\t/* ── two-layer focus ring · survives every surface in the system ── */")
	out.push(`\t--add-focus-ring-inner: ${L.focusRingInner};`)
	out.push(`\t--add-focus-ring-outer: ${L.focusRingOuter};`)

	out.push("\n\t/* ── typography families · size and leading are per-language, further down ── */")
	out.push(`\t--add-font-family-numeric: ${fontFamily.numeric};`)
	for (const [k, v] of Object.entries(fontWeight)) {
		out.push(`\t--add-font-weight-${kebab(k)}: ${v};`)
	}

	out.push("\n\t/* ── component (Tier 3) ── */")
	for (const [area, values] of Object.entries(C)) {
		for (const [k, v] of Object.entries(values)) out.push(`\t--add-${kebab(area)}-${kebab(k)}: ${v};`)
	}

	out.push("\n\t/* ── space · radius · elevation ── */")
	for (const [k, v] of Object.entries(space)) out.push(`\t--add-space-${k}: ${v};`)
	for (const [k, v] of Object.entries(radius)) out.push(`\t--add-radius-${kebab(k)}: ${v};`)
	for (const [k, v] of Object.entries(elevation)) out.push(`\t--add-elevation-${kebab(k)}: ${v};`)

	out.push("\n\t/* ── state · `deferred` is the sidebar 'Soon' read, not true disabled ── */")
	for (const [group, values] of Object.entries(state)) {
		for (const [k, v] of Object.entries(values)) out.push(`\t--add-${kebab(group)}-${kebab(k)}: ${v};`)
}

	out.push("}\n")

	// Per-language type scale. `<html lang>` is maintained by the direction
	// binding, so :lang() is reliable and needs no JS.
	out.push("/* ── per-language type scale ──────────────────────────────────────────── */")
	out.push("/* Arabic needs more size and looser leading than Latin at the same step.   */")
	for (const lang of SUPPORTED_LANGS) {
		out.push(`:root:lang(${lang}) {`)
		for (const [step, v] of Object.entries(typeScale[lang])) {
			out.push(`\t--add-font-size-${kebab(step)}: ${v.fontSize};`)
			out.push(`\t--add-line-height-${kebab(step)}: ${v.lineHeight};`)
		}
		out.push("}")
	}

	// Tailwind v4 reads its theme from CSS. Feeding the SAME variables is what
	// keeps Tailwind and naive-ui derived from one source.
	out.push("\n@theme inline {")
	for (const role of ["primary", "success", "warning", "danger", "info"]) {
		out.push(`\t--color-${role}-fill: var(--add-${role});`)
		out.push(`\t--color-${role}-text: var(--add-${role}-text);`)
		out.push(`\t--color-on-${role}: var(--add-${role}-on);`)
	}
	out.push("\t--color-surface: var(--add-surface);")
	out.push("\t--color-surface-raised: var(--add-surface-raised);")
	out.push("\t--color-surface-sunken: var(--add-surface-sunken);")
	out.push("\t--color-input-fill: var(--add-input-fill);")
	out.push("\t--color-border-subtle: var(--add-border);")
	out.push("\t--color-border-strong: var(--add-border-strong);")
	out.push("\t--color-text-primary: var(--add-text-primary);")
	out.push("\t--color-text-secondary: var(--add-text-secondary);")
	out.push("\t--color-text-muted: var(--add-text-muted);")
	out.push("\t--color-text-on-dark: var(--add-text-on-dark);")
	// Numerals face — `font-numeric` in Tailwind. Poppins has no tabular figures.
	out.push("\t--font-numeric: var(--add-font-family-numeric);")
	for (const k of Object.keys(brand)) out.push(`\t--color-brand-${kebab(k)}: var(--add-brand-${kebab(k)});`)
	for (const [k] of Object.entries(radius)) out.push(`\t--radius-add-${kebab(k)}: var(--add-radius-${kebab(k)});`)
	for (const [k] of Object.entries(elevation)) out.push(`\t--shadow-add-${kebab(k)}: var(--add-elevation-${kebab(k)});`)
	out.push("}\n")

	return out.join("\n")
}

// ════════════════════════════════════════════════════════════════════════════
// 3. Flutter / Dart transformer
// ════════════════════════════════════════════════════════════════════════════

function buildDart() {
	const hexToDart = h => {
		const v = String(h).replace("#", "")
		return v.length === 6 ? `0xFF${v.toUpperCase()}` : `0xFF${v.slice(0, 6).toUpperCase()}`
	}
	const isHex = v => typeof v === "string" && v.startsWith("#")
	const L = semantic.light
	const out = []

	out.push("// ignore_for_file: constant_identifier_names")
	out.push(`// ${banner("this file")}`)
	out.push("// Source: src/add-os/theme/tokens.ts\n")
	out.push("import 'dart:ui';\n")
	out.push("/// ADD OS brand primitives — verbatim from the ADD Brand Guideline 2026.")
	out.push("class AddBrand {")
	out.push("  AddBrand._();")
	for (const [k, v] of Object.entries(brand)) out.push(`  static const Color ${k} = Color(${hexToDart(v)});`)
	out.push("}\n")

	out.push("/// ADD OS semantic tokens — light mode.")
	out.push("/// Dark mode is out of scope for v1; add an `AddColorsDark` class when it lands.")
	out.push("class AddColors {")
	out.push("  AddColors._();")
	for (const [role, v] of Object.entries(L)) {
		if (isHex(v)) {
			out.push(`  static const Color ${role} = Color(${hexToDart(v)});`)
			continue
		}
		if (v && typeof v === "object") {
			for (const [sub, hex] of Object.entries(v)) {
				if (!isHex(hex)) continue
				const name = role + sub.charAt(0).toUpperCase() + sub.slice(1)
				out.push(`  static const Color ${name} = Color(${hexToDart(hex)});`)
			}
		}
	}
	out.push("}\n")

	out.push("/// Per-language type scale. Arabic runs larger and looser than Latin.")
	out.push("class AddTypeScale {")
	out.push("  AddTypeScale._();")
	for (const lang of SUPPORTED_LANGS) {
		for (const [step, v] of Object.entries(typeScale[lang])) {
			const n = `${lang}_${step}`
			out.push(`  static const double ${n}Size = ${Number.parseFloat(v.fontSize)};`)
			out.push(`  static const double ${n}LineHeight = ${Number.parseFloat(v.lineHeight)};`)
		}
	}
	out.push("}\n")

	out.push("class AddRadius {")
	out.push("  AddRadius._();")
	for (const [k, v] of Object.entries(radius)) out.push(`  static const double ${k} = ${Number.parseFloat(v)};`)
	out.push("}\n")

	out.push("class AddSpace {")
	out.push("  AddSpace._();")
	for (const [k, v] of Object.entries(space)) out.push(`  static const double s${k} = ${Number.parseFloat(v)};`)
	out.push("}")

	return out.join("\n")
}

// ════════════════════════════════════════════════════════════════════════════
// 4. Figma Tokens transformer  →  figma-tokens.json
// 5. Pinx runtime transformer   →  src/design-tokens.json
//
// Both must match the schema `src/theme/index.ts` already reads, so nothing
// downstream changes shape — only the values do.
//
// ── colors.dark is deliberately a COPY of colors.light ──────────────────────
// `getDefaultState()` picks Dark when the OS prefers dark, and `themeName` is
// persisted. Shipping a dark palette is out of scope, so a genuinely dark set
// here would render as a half-themed dark mode — exactly what was ruled out.
// Mirroring light means no configuration can produce an unthemed screen.
// The theme is ALSO pinned to Light at its source; this is the second belt.
// ════════════════════════════════════════════════════════════════════════════

function runtimeColors() {
	const L = semantic.light
	return {
		sidebarBackground: component.light.sidebar.background,
		bodyBackground: L.body,
		background: L.surface,
		backgroundSecondary: L.surfaceSunken,
		text: L.textPrimary,
		textSecondary: L.textSecondary,
		textTertiary: L.textMuted,
		border: L.border,
		hover: component.light.sidebar.itemHoverBackground,
		primary: L.primary.base,
		info: L.info.base,
		success: L.success.base,
		warning: L.warning.base,
		// Pinx names this slot `error`; ADD OS calls the role `danger`.
		error: L.danger.base,
		// Categorical data-viz slots — the brand colours left unassigned by Tier 2.
		extra1: brand.deepTeal,
		extra2: brand.smartOlive,
		extra3: brand.antiqueCopper,
		extra4: brand.softGrowthGreen
	}
}

/** Latin is the baseline for the runtime scale; :lang(ar) overrides it in CSS. */
const RUNTIME_LANG = "en"

function buildRuntimeTokens() {
	const s = typeScale[RUNTIME_LANG]
	const colors = runtimeColors()

	return {
		// JSON carries no comments, so the banner is a key. `src/theme/index.ts`
		// reads this file by named property, so an extra one is inert.
		$generated: banner("this file"),
		borderRadius: { default: radius.default, small: radius.small },
		lineHeight: { default: s.body.lineHeight },
		fontSize: { default: s.body.fontSize, cardTitle: s.lead.fontSize },
		fontWeight: {
			default: fontWeight.regular,
			strong: fontWeight.strong,
			cardTitle: fontWeight.strong
		},
		fontFamily: { default: fontFamily.ui, display: fontFamily.display, mono: fontFamily.mono },
		typography: {
			h1: { fontFamily: "{fontFamily.display}", fontSize: s.h1.fontSize, fontWeight: fontWeight.bold },
			h2: { fontFamily: "{fontFamily.display}", fontSize: s.h2.fontSize, fontWeight: fontWeight.bold },
			h3: { fontFamily: "{fontFamily.display}", fontSize: s.h3.fontSize, fontWeight: fontWeight.bold },
			h4: { fontFamily: "{fontFamily.display}", fontSize: s.h4.fontSize, fontWeight: fontWeight.strong },
			h5: { fontFamily: "{fontFamily.display}", fontSize: s.h5.fontSize, fontWeight: fontWeight.strong },
			h6: { fontFamily: "{fontFamily.default}", fontSize: s.h6.fontSize, fontWeight: fontWeight.medium },
			p: { fontFamily: "{fontFamily.default}", fontSize: "{fontSize.default}", lineHeight: s.body.lineHeight }
		},
		colors: { light: colors, dark: { ...colors } }
	}
}

function buildFigmaTokens() {
	const r = buildRuntimeTokens()
	const global = {
		"border-radius-default": { value: r.borderRadius.default, type: "borderRadius" },
		"border-radius-small": { value: r.borderRadius.small, type: "borderRadius" },
		"line-heights-default": { value: r.lineHeight.default, type: "lineHeights" },
		"font-sizes-default": { value: r.fontSize.default, type: "fontSizes" },
		"font-sizes-card-title": { value: r.fontSize.cardTitle, type: "fontSizes" },
		"font-weights-default": { value: r.fontWeight.default, type: "fontWeights" },
		"font-weights-strong": { value: r.fontWeight.strong, type: "fontWeights" },
		"font-weights-card-title": { value: r.fontWeight.cardTitle, type: "fontWeights" },
		"font-families-default": { value: r.fontFamily.default, type: "fontFamilies" },
		"font-families-display": { value: r.fontFamily.display, type: "fontFamilies" },
		"font-families-mono": { value: r.fontFamily.mono, type: "fontFamilies" }
	}

	for (const mode of ["light", "dark"]) {
		for (const [k, v] of Object.entries(r.colors[mode])) {
			global[`color-${mode}-${kebab(k)}`] = { value: v, type: "color" }
		}
	}
	for (const [tag, v] of Object.entries(r.typography)) {
		global[`typo-${tag}`] = { value: { ...v }, type: "typography" }
	}

	const ref = mode =>
		Object.fromEntries(
			Object.keys(r.colors[mode]).map(k => [`color-${kebab(k)}`, { value: `{color-${mode}-${kebab(k)}}`, type: "color" }])
		)

	// `$metadata` is Tokens Studio's own key, so the banner rides along in a slot
	// the plugin already understands rather than showing up as a stray token set.
	// `tokens-tool.js` reads only .global/.light/.dark, so it is inert there too.
	return {
		$metadata: {
			generated: banner("this file"),
			tokenSetOrder: ["global", "light", "dark"]
		},
		global,
		light: ref("light"),
		dark: ref("dark")
	}
}

// ════════════════════════════════════════════════════════════════════════════
// write
// ════════════════════════════════════════════════════════════════════════════

const targets = [
	[path.join(THEME_DIR, "tokens.json"), `${JSON.stringify(buildDtcg(), null, "\t")}\n`],
	[path.join(THEME_DIR, "tokens.generated.css"), buildCss()],
	[path.join(THEME_DIR, "tokens.dart"), `${buildDart()}\n`],
	[path.join(ROOT, "figma-tokens.json"), `${JSON.stringify(buildFigmaTokens(), null, "\t")}\n`],
	[path.join(ROOT, "src", "design-tokens.json"), `${JSON.stringify(buildRuntimeTokens(), null, "\t")}\n`]
]

for (const [file, contents] of targets) {
	await fs.outputFile(file, contents)
	console.log(`  ✓ ${path.relative(ROOT, file).replace(/\\/g, "/")}`)
}

console.log(`\n  ${Object.keys(brand).length} brand primitives · modes: ${[...THEME_MODES].join(", ")}`)
if (!DARK_MODE_SUPPORTED) {
	console.log("  dark mode: OUT OF SCOPE — colors.dark mirrors light so nothing can render half-themed.")
}
process.exit(0)
